#!/usr/bin/env bash
# shellcheck disable=SC2154
# Script that configures Nginx server with a custom header and HAproxy load balancer

apt-get -y update
apt-get -y install nginx
service nginx start
sudo apt install -y haproxy

cat >> /etc/haproxy/haproxy.cfg << EOF
frontend Local_Server
	bind *:80
	mode http
	default_backend Web_Servers
backend Web_Servers
	balance roundrobin
	mode http
	server web-01 100.25.180.82:80 check
	server web-02 54.162.76.36:80 check
EOF

service haproxy restart