#!/usr/bin/env bash
# Loops from 1 to 10 and displays:
#   "bad luck" for the 4th iteration
#   "good luck" for the 8th iteration
#   "Best School" for all other iterations

count=0

while (( count <= 10 ))
  do
    if (( count == 4 ))
    then
      echo "bad luck"
      (( count++ ))
    elif (( count == 8 )); 
    then
      echo "good luck"
      (( count++ ))
    else
      echo "Best School"
      (( count++ ))
    fi
  done