#!/usr/bin/env bash
# Loops from 1 to 10 and displays:
#   "bad luck" for the 4th iteration
#   "good luck" for the 8th iteration
#   "Best School" for all other iterations

count=0

while (( count < 21 ))
do
	if (( count == 4 ))
	then
		echo "bad luck from China"
		(( count++ ))
	elif (( count == 9 ))
	then
		echo "bad luck from Japan" 
		(( count++ ))
	elif (( count == 17 ))
	then
		echo "bad luck from Italy"
		(( count++ ))
	else
		echo $count
		(( count++ ))
	fi
done